language: objective-c
xcode_project: TravisDemo.xcodeproj
xcode_scheme: TravisDemo
xcode_sdk: iphonesimulator
osx_image: xcode7.2
script:
  - xctool build -project TravisDemo.xcodeproj -scheme TravisDemo -sdk iphonesimulator
after_success:
  - bash <(curl -s https://codecov.io/bash)
